---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-ns-cleaner
  namespace: kube-ns-cleaner
spec:
  schedule: "0 0 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kube-ns-cleaner
          containers:
          - name: kube-ns-cleaner
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
              - "sh"
              - "/opt/script/ns-for-deleting.sh"
            volumeMounts:
            - mountPath: /opt/script/ns-for-deleting.sh
              name: kube-ns-cleaner-config
              subPath: ns-for-deleting.sh
              readOnly: false
            - mountPath: /opt/script/ns-not-for-deleting.yml
              name: kube-ns-cleaner-config
              subPath: ns-not-for-deleting.yml
          volumes:
          - configMap:
              name: kube-ns-cleaner-config
            name: kube-ns-cleaner-config
          restartPolicy: Never
