---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-ns-cleaner-config
  namespace: kube-ns-cleaner
  labels:
    app: kube-ns-cleaner
data:
  ns-not-for-deleting.yml: |
    default
    ingress-nginx
    kube-node-lease
    kube-ns-cleaner
    kube-public
    kube-system
    monitoring
    reloader

  ns-for-deleting.sh: |
    #!/bin/bash

    ns_not_for_deleting=$(cat '/opt/script/ns-not-for-deleting.yml')
    ns_for_deleting=$(kubectl get ns |awk '{ if (length($3) >= 3 && $3 !~ "s" && $3 !~ "m" && $3 !~ "h" && $2 == "Active") print $1 }')

    for ns in $ns_for_deleting; do
    echo $ns_not_for_deleting | grep -w $ns >/dev/null
    if [ $? = 0 ]; then
    continue
    fi
    kubectl delete ns $ns
    done
    echo "\e[32mkube-ns-cleaner finished\e[0m"
