---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-ns-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ns-cleaner-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - pods/exec
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - replicasets
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets/scale
      - statefulsets
    verbs: ["*"]
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs: ["*"]
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-ns-cleaner
subjects:
  - kind: ServiceAccount
    name: kube-ns-cleaner
    namespace: kube-ns-cleaner
roleRef:
  kind: ClusterRole
  name: kube-ns-cleaner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ns-cleaner
  namespace: kube-ns-cleaner
