apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ns-cleaner.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - pods/exec
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - replicasets
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["*"]
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets/scale
      - statefulsets
    verbs: ["*"]
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs: ["*"]
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs: ["*"]
